Tried adding a second barrier to make sure all ranks know the counts before trying to distribute data. @beckermr - this was worth trying, though I'm pretty sure both functions implement their own barrier internally. Since nothing else is jumping out, I guess the next thing to do is to check more comprehensively the consistency between the input data and the send/receive counts, so that we can at least rule that out. So far I've only done that roughly, by verifying the correct min/max xyz for each rank.
For posterity this commit sometimes produces the same Traceback as usual:

$ mpiexec -n 2 python chopit.py 2 2 2 1000 30 mass core_id

Traceback (most recent call last):
  File "chopit.py", line 79, in <module>
    comm.Alltoallv([sendbuf, send_counts], [recv_buff, recv_counts])
  File "mpi4py/MPI/Comm.pyx", line 677, in mpi4py.MPI.Comm.Alltoallv
mpi4py.MPI.Exception: MPI_ERR_TRUNCATE: message truncated